server:
  host: 127.0.0.1
  port: 25565

motd: |
  &bmc-project &8:: &4ZERO
  &8develop by &7DmitriyMX

disconnect-reason: '&4Server is not available.'

players:
  max-online: 0
  online: 0

icon:
  enable: true
  path: src/main/resources/favicon.png