server:
  host: 127.0.0.1
  port: 25565

motd: |
  &bmc-project &8:: &4ZERO
  &8develop by &7DmitriyMX

disconnect-reason: '&4Server is not available.'

players:
  max-online: 0
  online: 0

# Размер значка: 64x64 px
icon:
  enable: false
  path: favicon.png

world:
  view-distance: 1